const actionIds = {
    APP_GET_TOP_STORES : '[APP] GET TOP STORES',
    APP_GET_TOP_CATEGORIES : '[APP] GET TOP CATEGORIES',
    AUTH_EXTERNAL_SIGNIN : '[AUTH] EXTERNAL SIGN IN',
    AUTH_SIGNIN : '[AUTH] SIGN IN',
    AUTH_SIGNUP : '[AUTH] SIGN UP',
    AUTH_VERIFY_EMAIL : '[AUTH] VERIFY EMAIL',
    AUTH_FORGOT_PASSWORD : '[AUTH] FORGOT PASSWORD',
    AUTH_RESET_PASSWORD : '[AUTH] RESET PASSWORD',
    ONLINE_CASHBACKS_GET_STORE_DETAILS : '[ONLINE CASHBACKS] GET STORE DETAILS' ,
    ONLINE_CASHBACKS_GET_STORES_BY_CATEGORY_ID : '[ONLINE CASHBACKS] GET STORES BY CATEGORY ID' ,
    ONLINE_CASHBACKS_GET_ALL_CATEGORIES : '[ONLINE CASHBACKS] GET ALL CATEGORIES'
};

export default actionIds;